# Generated by Django 4.1.7 on 2023-03-17 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleur', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='mod_file',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='rom',
            name='rom_file',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
