# Generated by Django 4.1.7 on 2023-03-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleur', '0005_alter_comment_message_alter_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod',
            name='mod_file',
        ),
        migrations.RemoveField(
            model_name='rom',
            name='rom_file',
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
