# Generated by Django 4.1.7 on 2023-03-21 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleur', '0006_remove_mod_mod_file_remove_rom_rom_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='mod_file',
            field=models.FileField(blank=True, upload_to='media/'),
        ),
    ]
