# Generated by Django 4.1.7 on 2023-03-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleur', '0007_mod_mod_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='mod_file',
            field=models.FileField(default=None, max_length=250, upload_to='media/'),
        ),
    ]
