# Generated by Django 4.1.7 on 2023-03-21 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleur', '0008_alter_mod_mod_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod',
            name='mod_file',
        ),
    ]
