# Generated by Django 4.1.7 on 2023-03-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleur', '0009_remove_mod_mod_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mod',
            name='mod_credits',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
