# Generated by Django 4.1.7 on 2023-03-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleur', '0010_mod_mod_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='mod_credits',
            field=models.CharField(max_length=150),
        ),
    ]
